sudo: true
dist: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
addons:
  chrome: stable
before_install:
- openssl aes-256-cbc -K $encrypted_2af42af72c58_key -iv $encrypted_2af42af72c58_iv
  -in assets/server.key.enc -out assets/server.key -d
- wget -qO- $URL | tar xJf -
- ./sfdx/install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- heroku plugins:install salesforce-lightning-cli
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_AUTOUPDATE_DISABLE=true- export PATH=./sfdx/$(pwd):$PATH
- sfdx plugins:install salesforcedx@pre-release
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a BetaHub
script:
- sfdx force:org:create -v BetaHub -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human
- lintout=$(sfdx force:lightning:lint lightning-component-tests/main/default/aura/);if
  [[ $lintout =~ .*problem.*error.*warning ]]; then echo "$lintout"; false; fi
- sfdx force:lightning:test:run
- sfdx force:org:delete -u ciorg -p
